plugins = ["!error"]
interpreter = "0.23.4"


[[fetch]]
files = ["GTA_SA_Save_Game_Editor.py", "__init__.py", "offsets.py"]
from = "https://raw.githubusercontent.com/Saketh-Chandra/GTA_SA_Save_Game_EditorPy/dev/GTA_SA_Save_Game_Editor/"
to_folder = "GTA_SA_Save_Game_Editor"
