terminal = false

[splashscreen]
autoclose = true

[[fetch]]
files = ["GTA_SA_Save_Game_Editor.py"]
from = "https://raw.githubusercontent.com/Saketh-Chandra/GTA_SA_Save_Game_EditorPy/master/"

# [[interpreters]]
# src = "https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.js"
# name = "pyodide-0.21.2"
# lang = "python"
